import React, { useState } from "react";
import StyledComponentsRegistry from "@/app/registry";
import App from "./App";
import Script from "next/script";

export const metadata = {
    title: "Inclusão",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <StyledComponentsRegistry>
            <App>
                {children}
                <Script src="https://vlibras.gov.br/app/vlibras-plugin.js" />
            </App>
        </StyledComponentsRegistry>
    );
}
